defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: peatio.dev
  URL_SCHEMA: http
  SESSION_EXPIRE: 120
  API_WHITELIST: []
  ADMIN: 'admin@peatio.dev,admin@example.com'
  TIMEZONE: 'Beijing'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_DOMAIN: YOUR_SMTP_DOMAIN
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_USERNAME: YOUR_SMTP_USERNAME
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  # SMTP_DOMAIN: '127.0.0.1'
  # SMTP_ADDRESS: 'smtp.gmail.com'
  # SMTP_USERNAME: 'arvindyuvasoft112@gmail.com'
  # SMTP_PASSWORD: 'arvindyuva'

  SYSTEM_MAIL_FROM: system@peatio.dev
  SYSTEM_MAIL_TO: group@peatio.dev

  # WebSocket Streaming API settings
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  # PUSHER_APP: 65910
  # PUSHER_KEY: 50d404c35db92d736a57
  # PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 82305
  PUSHER_KEY: 772dd6f223d192351ed7
  PUSHER_SECRET: 943863b1a9ababb547f0
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  # TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  # TWILIO_SID: YOUR_TWILIO_SID
  # TWILIO_TOKEN: YOUR_TWILIO_TOKEN
  TWILIO_NUMBER: '9630595488'
  TWILIO_SID: 'AC31ae43cecd365737a7fe3ac63bc5825a'
  TWILIO_TOKEN: '91c964550a415a5615d32dca4d815a8a'  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
