development: &defaults
  adapter: mysql2
  database: peatio_development
  username: root
  password:
  pool: 10
  reconnect: true
  socket: /var/lib/mysql/mysql.sock
  host: 127.0.0.1

test:
  <<: *defaults
  database: peatio_test

production:
  <<: *defaults
  database: peatio_development
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password:
#   socket: /opt/lampp/var/mysql/mysql.sock

# development:
#   <<: *default
#   database: peatio_development